### PR TITLE
Fixed Incorrect help message

### PR DESCRIPTION
**Pull request by Aman-Mandal**

### CODE REVIEW

**Comment by sgoudham** [comment]
Hi, not sure if you've finished with your changes are not but the help message should be changed within the code also which is located here -> https://github.com/sgoudham/uwuifyy/blob/v0.3.0/src/main.rs#L80

**Comment by Aman-Mandal** [comment]
Ohh so sorry , I didn't knew !! I ll do it right now

**Comment by Aman-Mandal** [comment]
I dont know why am unable to find my local branch.. so created a new PR !!  I hope u won't mind. Am just a beginner :)

**Comment by sgoudham** [comment]
No worries, I'll update the title of the other one

**Pull request closed without merging**
